### PR TITLE
Support for pagination on project graph, light mode, SQLite migr.

### LINKED ISSUE #9: Timer indicator on home page controls
Add the timer indicator in the bottom controls in home page.
Thanks to @fabiosangregorio

### PR DESCRIPTION
**Pull request by spacycoder**
Added
* Support for stepping changing week in project bar chart
* Light mode
* Timer indicator on home page controls. Closes #9 

Swapped HIVE with SQLITE(https://moor.simonbinder.eu/). **Note!** this change means that users will lose their existing data.

### CODE REVIEW

**Comment by GiorgioBertolotti** [comment]
Hello, I was testing all the features and the refactoring you've done and I love everything, great job!

Unfortunately I noticed that probably you've changed the management of the activities and with this changes it happens that when you have a running timer and you close and re-open the app you'll eventually lose the timer state, can you fix it?

**Steps to reproduce:**

1. Open a project and start a timer with notification enabled
2. Close the app
3. Tap on the notification

As you can see now there's no longer the timer running.

**Comment by spacycoder** [comment]
Sorry for taking so long, been busy with school and stuff. But it should persist the timer state now.

**Comment by GiorgioBertolotti** [comment]
Hello Lars, between yesterday and today I've cherry-picked part of your development on the project to keep all the great improvements (like improvements to project dialog, to bar chart, themes, etc.) and at the same time continue using Hive as DB so the users won't lose their data...
Unfortunately I didn't cherry picked all the management of services and the RxDart work because I've never used it, so I didn't know how to isolate it from the SQLite database you've used.
Do you think it could be possible to you to add to the current state of the project the RxDart behavior (as you already did in your fork) keeping Hive as DB?
Thanks again for your time!
Giorgio

**Comment by spacycoder** [comment]
Hello Giorgio!

I switched from hive to sqlite mostly to get better query capabilities. This could enable future features like heatmap calender view, stats across projects and more.

But I can refactor to use hive if you want. This would however take a some time, as I will be quite busy for the next couple of weeks.

**Comment by spacycoder** [comment]
Might also be possible to do a migration from hive to sqlite by checking if the user has something in the hive database, and then push this data to the sqlite database.

**Comment by GiorgioBertolotti** [comment]
> Might also be possible to do a migration from hive to sqlite by checking if the user has something in the hive database, and then push this data to the sqlite database.

If you could take some time when you can to work on this second option it would be great!
Also in the last commit I added a dialog for editing the activities, could you include it in your next developments if possible?
Thanks again and sorry if I'm asking you so much!

**Comment by spacycoder** [comment]
I'll give it a try when I have time ;)

**Comment by spacycoder** [comment]
Hello Giorgio, i have added migration from Hive to Sqlite now. So users should be able to keep their data.

**Comment by GiorgioBertolotti** [comment]
Hello Lars, I've tested it and works perfectly!
If you don't mind I'm going to change a few things to improve the user experience, thanks a lot for your work, great job!

**Pull request merged**
